services:
  nrf:
    image: nordicplayground/nrfconnect-sdk:v2.2-branch
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ..:/workdir/project
      # Make the bash prompt beautiful
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    tmpfs:
      - /tmp
    environment:
      - HOME=/tmp
      - ZEPHYR_BASE=/workdir/project/zephyr
    working_dir: /workdir/project/application
