services:
  nrf:
    image: zephyrprojectrtos/ci:v0.26.11
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ..:/workdir/project
    tmpfs:
      - /tmp
    environment:
      - ZEPHYR_BASE=/workdir/project/zephyr
    working_dir: /workdir/project/application
