manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf-next
      remote: ncs
      revision: v2.4.99-cs3
      import: true
    - name: zephyr-my-boards
      url: https://github.com/fgervais/zephyr-my-boards
      revision: 76c30ba22ea30c0b560b613889787a689535fba3
      path: myboards
  self:
    path: application

